### ISSUE TITLE
[charm] include shell completions support

### ISSUE THREAD

**Issue by yermulnik** [charmbracelet/homebrew-tap#2]
Since `charm` supports auto-generation of shell completions for different shells it would be great to have this bundled into brew formulae so that files for each supported shell is created during installation.

**Comment by yermulnik** [comment]
E.g. like this https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/kubernetes-cli.rb#L33-L39

**Comment by aymanbagabas** [comment]
Shell completions are now included in brew formulas.

**Comment by yermulnik** [comment]
Cool. Thanks!
